routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['middleware' => ['web']], function () {
    Route::get('/login', ['as' =>'login', 'uses' =>'AuthController@login']);
    Route::post('/handleLogin', ['as' =>'handleLogin', 'uses' =>'AuthController@handleLogin']);

    Route::get('/home', ['middleware'=>'auth', 'as' =>'home', 'uses' =>'UsersController@home']);
    
     Route::get('/logout','AuthController@logout')->name('logout');
	//Route::get('/logout', ['as' =>'logout', 'uses' =>'AuthController@logout']);
	Route::resource('users', 'UsersController', ['only' => ['create', 'edit','update', 'store']]);

   

    Route::get('/account', ['middleware'=>'auth', 'as' =>'account', 'uses' =>'UsersController@account']);
    Route::get('/account', 'DataController@showName');

    Route::get('/accountProject', 'DataController@showproject');
//Wyswietlanie strony z formularzem dodawania
    Route::get('/addProject', 'DataController@showAddproject');
    Route::post('/addProject', 'DataController@store');

    Route::get('/loveProject', 'DataController@showlove');

    Route::get('/changeInfo', 'DataController@showChInfo');
    Route::get('/changeInfo', 'DataController@showInfo');
   


    Route::get('/changePass', 'DataController@showChPass');
    Route::get('/changePass', 'DataController@showPass');


//wyświetlanie projektów w podkategoriach
    Route::get('/projects/projectCategory/{id}', 'ProjectController@index');

// wyświetlanie informacji o poszczególnym projekcie
    Route::get('/projects/aboutProject/{id}', 'ProjectController@about');

// realizacja stopki:
    Route::get('/contact', 'FooterController@index');


//Panel administratora:
     Route::get('/admin', 'AdminController@showAdmin');
     Route::get('/allProjects', 'AdminController@showAllP');
     Route::get('/allUsers', 'AdminController@showAllU');
     Route::get('/stats', 'AdminController@showStats');

//Usuwanie z ulubionych:
     Route::get('/projects/aboutProject/{id}/deleteF', 'ProjectController@deleteF');

//Dodawanie do ulubionych:
     Route::get('/projects/aboutProject/{id}/addF', 'ProjectController@addF');

//Dodawanie komentarzy:
     Route::post('/projects/aboutProject/{id}', 'ProjectController@addComment');

//Dodawanie oceny:
 //    Route::post('/projects/aboutProject/{id}', 'ProjectController@addGrade');

//Strona kontakt:
     Route::get('/contact', 'PageController@showContact');

//Wyślij wiadomość:
     Route::post('/contact', 'PageController@sendMessage');


     //English version


    Route::get('/loginE', ['as' =>'login', 'uses' =>'AuthControllerE@login']);
    Route::post('/handleLogin', ['as' =>'handleLogin', 'uses' =>'AuthControllerE@handleLogin']);

    Route::get('/homeE', ['middleware'=>'auth', 'as' =>'home', 'uses' =>'UsersControllerE@home']);
    
     Route::get('/logoutE','AuthControllerE@logout')->name('logout');
    //Route::get('/logout', ['as' =>'logout', 'uses' =>'AuthController@logout']);
    Route::resource('users', 'UsersControllerE', ['only' => ['create', 'edit','update', 'store']]);

   

    Route::get('/accountE', ['middleware'=>'auth', 'as' =>'account', 'uses' =>'UsersControllerE@account']);
    Route::get('/accountE', 'DataControllerE@showName');

    Route::get('/accountProjectE', 'DataControllerE@showproject');
//Wyswietlanie strony z formularzem dodawania
    Route::get('/addProjectE', 'DataControllerE@showAddproject');
    Route::post('/addProjectE', 'DataControlleEr@store');

    Route::get('/loveProjectE', 'DataControllerE@showlove');

    Route::get('/changeInfoE', 'DataControllerE@showChInfo');
    Route::get('/changeInfoE', 'DataControllerE@showInfo');
   


    Route::get('/changePassE', 'DataControllerE@showChPass');
    Route::get('/changePassE', 'DataControllerE@showPass');


//wyświetlanie projektów w podkategoriach
    Route::get('/projectsENG/projectCategory/{id}', 'ProjectControllerE@index');

// wyświetlanie informacji o poszczególnym projekcie
    Route::get('/aboutProjectE/{id}', 'ProjectControllerE@about');

// realizacja stopki:
    Route::get('/contactE', 'FooterControllerE@index');


//Panel administratora:
     Route::get('/adminE', 'AdminControllerE@showAdmin');
     Route::get('/allProjectsE', 'AdminControllerE@showAllP');
     Route::get('/allUsersE', 'AdminControllerE@showAllU');
     Route::get('/statsE', 'AdminControllerE@showStats');

//Usuwanie z ulubionych:
     Route::get('/projectsE/aboutProjectE/{id}/deleteF', 'ProjectControllerE@deleteF');

//Dodawanie do ulubionych:
     Route::get('/aboutProjectE/{id}/addF', 'ProjectControllerE@addF');

//Dodawanie komentarzy:
     Route::post('/aboutProjectE/{id}', 'ProjectControllerE@addComment');

//Dodawanie oceny:
     Route::post('/aboutProjectE/{id}', 'ProjectControllerE@addGrade');

//Strona kontakt:
     Route::get('/contactE', 'PageControllerE@showContact');

//Wyślij wiadomość:
     Route::post('/contactE', 'PageControllerE@sendMessage');


});

resources/views/layouts/master.blade.php
<!DOCTYPE html>

<head>
    <meta charset="utf-8">

   
    <title>ZróbToSam</title>
    

    <!-- Fonts -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700&subset=latin,latin-ext" rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">


    <!-- Styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ URL::asset('/css/bootstrap-theme.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/bootstrap-theme.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/bootstrap.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/m.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/register.css')}}" rel="stylesheet">
   
    <link href="{{ URL::asset('/css/contact.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/grid.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/socialicon.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/media-carousel.css')}}" rel="stylesheet">


    <script src="js/category.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body>

     <header class="header">
<?php 
  if(Auth::check()){

  ?>
              <div class="container">
                <nav class="navbar1 navbar-default navbar-fixed-top">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar5">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                     
                    </div>
                    <div id="navbar5" class="navbar-collapse collapse">
                      <ul class="nav navbar-nav navbar-right">
                        <li><a href="/account"><span class="glyphicon glyphicon-user"></span> Moje konto</a></li>
                        <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Wyloguj się</a></li>
                      </ul>
                    </div>
                    <!--/.nav-collapse -->
                  </div>
                  <!--/.container-fluid -->
                </nav>

              </div>

<?php
}
else
{
?>
   <div class="container">
                <nav class="navbar1 navbar-default navbar-fixed-top">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar5">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                     
                    </div>
                    <div id="navbar5" class="navbar-collapse collapse">
                      <ul class="nav navbar-nav navbar-right">
                        <li><a href="/users/create"><span class="glyphicon glyphicon-user"></span> Rejestracja</a></li>
                        <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Zaloguj się</a></li>
                      </ul>
                    </div>
                    <!--/.nav-collapse -->
                  </div>
                  <!--/.container-fluid -->
                </nav>

              </div>
<?php
}
?>
<center>
      <br>   
  <a href="home">  
    <img src="/../img/logo.png" class="img-responsive" width="750" height="400"> 
  </a>
<hr>
</center>

    </header>

    <!-- wrapper -->
    <div class="site-wrappper">

        <!-- .container -->
        <div class="container site-content">

{{--       <ul class="nav nav-pills">
      @if(\Auth::check())

      <li>
        {{link_to_route('logout', 'Logout')}}
      </li>
      @else
          <li>
        {{link_to_route('login', 'Login')}}
      </li>

      </ul>

      @endif

       <li>
        {{link_to_route('users.create', 'Nowy uzytkownik')}}
      </li> --}}
            @yield('content')
            
        </div><!-- end of .container -->
        
    </div><!-- end of wrapper -->
    

    <!-- Footer -->
   
    <footer class="footer">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<!-- // -->   
  <hr />
<div class="container">
 
        <div class="text-center center-block">
        <p class="foot">
              <a href="#"><i class="foot1">Informacje</i></a>
              <a href="/../contact"><i class="foot1">Kontakt</i></a>
              <a href="#"><i class="foot1">Regulamin</i></a>
              <a href="homeE"> <i class="foot1">English</i></a>
         </p>
        </div>

        <div class="text-center center-block">
              <a href="#"><i class="fa fa-facebook-square fa-3x social"></i></a>
              <a href="#"><i class="fa fa-google-plus-square fa-3x social"></i></a>
              <a href="#"><i class="fa fa-envelope-square fa-3x social"></i></a>
        </div>
   
</div>
  <hr />
    </footer>


    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/layouts/masterE.blade.php
<!DOCTYPE html>

<head>
    <meta charset="utf-8">

   
    <title>ZróbToSam</title>
    

    <!-- Fonts -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700&subset=latin,latin-ext" rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">


    <!-- Styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ URL::asset('/css/bootstrap-theme.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/bootstrap-theme.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/bootstrap.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/m.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/register.css')}}" rel="stylesheet">
   
    <link href="{{ URL::asset('/css/contact.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/grid.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/socialicon.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('/css/media-carousel.css')}}" rel="stylesheet">


    <script src="js/category.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body>

     <header class="header">
<?php 
  if(Auth::check()){

  ?>
              <div class="container">
                <nav class="navbar1 navbar-default navbar-fixed-top">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar5">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                     
                    </div>
                    <div id="navbar5" class="navbar-collapse collapse">
                      <ul class="nav navbar-nav navbar-right">
                        <li><a href="/accountE"><span class="glyphicon glyphicon-user"></span> My account</a></li>
                        <li><a href="/logoutE"><span class="glyphicon glyphicon-log-in"></span> Sign out</a></li>
                      </ul>
                    </div>
                    <!--/.nav-collapse -->
                  </div>
                  <!--/.container-fluid -->
                </nav>

              </div>

<?php
}
else
{
?>
   <div class="container">
                <nav class="navbar1 navbar-default navbar-fixed-top">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar5">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                     
                    </div>
                    <div id="navbar5" class="navbar-collapse collapse">
                      <ul class="nav navbar-nav navbar-right">
                        <li><a href="/usersENG/createE"><span class="glyphicon glyphicon-user"></span> Registration</a></li>
                        <li><a href="/loginE"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
                      </ul>
                    </div>
                    <!--/.nav-collapse -->
                  </div>
                  <!--/.container-fluid -->
                </nav>

              </div>
<?php
}
?>
<center>
      <br>   
  <a href="homeE">  
    <img src="/../img/logo.png" class="img-responsive" width="750" height="400"> 
  </a>
<hr>
</center>

    </header>

    <!-- wrapper -->
    <div class="site-wrappper">

        <!-- .container -->
        <div class="container site-content">

{{--       <ul class="nav nav-pills">
      @if(\Auth::check())

      <li>
        {{link_to_route('logout', 'Logout')}}
      </li>
      @else
          <li>
        {{link_to_route('login', 'Login')}}
      </li>

      </ul>

      @endif

       <li>
        {{link_to_route('users.create', 'Nowy uzytkownik')}}
      </li> --}}
            @yield('content')
            
        </div><!-- end of .container -->
        
    </div><!-- end of wrapper -->
    

    <!-- Footer -->
   
    <footer class="footer">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<!-- // -->   
  <hr />
<div class="container">
 
        <div class="text-center center-block">
        <p class="foot">
              <a href="#"><i class="foot1">Information</i></a>
              <a href="/../contactE"><i class="foot1">Contact</i></a>
              <a href="#"><i class="foot1">Statute</i></a>
              <a href="/../home"><i class="foot1">Polish</i></a>
         </p>
        </div>

        <div class="text-center center-block">
              <a href="#"><i class="fa fa-facebook-square fa-3x social"></i></a>
              <a href="#"><i class="fa fa-google-plus-square fa-3x social"></i></a>
              <a href="#"><i class="fa fa-envelope-square fa-3x social"></i></a>
        </div>
   
</div>
  <hr />
    </footer>


    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>